version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-law-backend
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      APP_HOST: ${APP_HOST}
      APP_PORT: ${APP_PORT}
      APP_RELOAD: ${APP_RELOAD}
      DASHSCOPE_API_KEY: ${DASHSCOPE_API_KEY}
      DASHSCOPE_BASE_URL: ${DASHSCOPE_BASE_URL}
      DEFAULT_MODEL: ${DEFAULT_MODEL}
      FILES_ROOT: ${FILES_ROOT:-/app/files}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./storage/files:/app/files
    command: >
      sh -c "
      uvicorn app.main:app --host ${APP_HOST} --port ${APP_PORT} --reload
      "
    dns:
      - 8.8.8.8
      - 223.5.5.5

  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice
    restart: always
    ports:
      - "8080:80"
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=ZjS2mNT5nQZV1TJsIRxI3yLEm8ejnqD5
      - JWT_INBOX_ENABLED=true
      - JWT_INBOX_SECRET=ZjS2mNT5nQZV1TJsIRxI3yLEm8ejnqD5
      - JWT_OUTBOX_ENABLED=true
      - JWT_OUTBOX_SECRET=ZjS2mNT5nQZV1TJsIRxI3yLEm8ejnqD5
      - allowPrivateIPAddress=true
      - allowMetaIPAddress=true
      - LANG=zh-ch
      - DS_CORS_ORIGIN=http://localhost:5001
    volumes:
      - ./onlyoffice/data:/var/www/onlyoffice/Data
      - ./onlyoffice/logs:/var/log/onlyoffice
      - ./onlyoffice/lib:/var/lib/onlyoffice
      - ./fonts:/usr/share/fonts/truetype/custom   # ←★ 加这个

  react-frontend:
    image: nginx:alpine
    container_name: react-frontend
    ports:
      - "5001:80"  # 原前端访问端口
    volumes:
      - /home/deep/ailawapp/dist:/usr/share/nginx/html:ro
    restart: always
    dns:
      - 8.8.8.8
      - 223.5.5.5

  static-page:
    image: nginx:alpine
    container_name: static-page
    ports:
      - "5000:80"  # 宣传页访问端口1
    volumes:
      - /home/deep/ailawapp:/usr/share/nginx/html:ro
      - /home/deep/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
    dns:
      - 8.8.8.8
      - 223.5.5.5
